### ISSUE TITLE
Failing to activate plugin

### ISSUE THREAD

**Issue by sbangnielsen** [iseqqavoq/APSIS-Pro-User-Subscriptions#1]
The plugin will not activate, if parent plugin is downloaded from wordpress.org

The problem is that .org-plugin has a different path than the github-version, so the check for parent-plugin fails.

/wp-content/plugins/APSIS-Pro-for-WP/apsis-pro-for-wp.php
vs
/wp-content/plugins/apsis-pro-for-wp/apsis-pro-for-wp.php

It’s worth considering to check for Class or Function instead, since plugin path is unreliable in many cases.

https://pippinsplugins.com/checking-dependent-plugin-active/

**Comment by mattiasiqq** [comment]
Fixed.
