### ISSUE TITLE
Fails after updating parent plugin

### ISSUE THREAD

**Issue by sbangnielsen** [iseqqavoq/APSIS-Pro-User-Subscriptions#5]
Please consistently use lowercase-letter, when naming directories and folders.

After updating the parent-plugin to 1.0.8 (from WordPress.org) this plugin can no longer be activated because of line 58

`require_once ABSPATH . '/wp-content/plugins/APSIS-Pro-for-WP/apsis-pro-for-wp.php';`

which should be
`require_once ABSPATH . '/wp-content/plugins/apsis-pro-for-wp/apsis-pro-for-wp.php';`

The problem is that directory naming is not consistent from GitHub to WordPress.org

**Comment by iseqqavoq** [comment]
Thanks for the feedback. Pull request merged and the two github repositories have been renamed with lowercase-letters.
